CREATE TABLE "LegalTerms" (
	"id" BIGINT PRIMARY KEY DEFAULT generate_tsid('LegalTerms'),
	"text" TEXT NOT NULL,
	"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER "LegalTerms_updated_at"
BEFORE UPDATE ON "LegalTerms"
FOR EACH ROW EXECUTE FUNCTION updated_at();
